name: 'Repo Relay'
description: 'GitHub-Discord integration bot that tracks PRs, CI, issues, and releases with threaded updates'
author: 'Christopher Pishaki'

branding:
  icon: 'message-circle'
  color: 'purple'

inputs:
  discord_bot_token:
    description: 'Discord bot token'
    required: true
  channel_prs:
    description: 'Discord channel ID for PR notifications'
    required: true
  channel_issues:
    description: 'Discord channel ID for issue notifications (defaults to channel_prs)'
    required: false
  channel_releases:
    description: 'Discord channel ID for release notifications (defaults to channel_prs)'
    required: false
  state_dir:
    description: 'Directory for SQLite state persistence (default: ~/.repo-relay)'
    required: false
    default: '~/.repo-relay'
  github_token:
    description: 'GitHub token for API access (review detection). Defaults to github.token'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ${{ github.action_path }}/package-lock.json

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci --omit=dev

    - name: Run repo-relay
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        DISCORD_BOT_TOKEN: ${{ inputs.discord_bot_token }}
        DISCORD_CHANNEL_PRS: ${{ inputs.channel_prs }}
        DISCORD_CHANNEL_ISSUES: ${{ inputs.channel_issues }}
        DISCORD_CHANNEL_RELEASES: ${{ inputs.channel_releases }}
        GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
        STATE_DIR: ${{ inputs.state_dir }}
      run: node dist/cli.js
